package com.uttam.education.entity.model;
// Generated Jul 17, 2015 10:52:06 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Long addressId;
	private String adrLine1;
	private String adrLine2;
	private String cityNm;
	private String stateCd;
	private String zipCd;
	private Date crtdDt;
	private String createUsrId;
	private Date updtDt;
	private String updtUserId;

	public Address() {
	}

	public Address(Long addressId, String adrLine1, Date crtdDt, String createUsrId) {
		this.addressId = addressId;
		this.adrLine1 = adrLine1;
		this.crtdDt = crtdDt;
		this.createUsrId = createUsrId;
	}

	public Address(Long addressId, String adrLine1, String adrLine2, String cityNm, String stateCd, String zipCd,
			Date crtdDt, String createUsrId, Date updtDt, String updtUserId) {
		this.addressId = addressId;
		this.adrLine1 = adrLine1;
		this.adrLine2 = adrLine2;
		this.cityNm = cityNm;
		this.stateCd = stateCd;
		this.zipCd = zipCd;
		this.crtdDt = crtdDt;
		this.createUsrId = createUsrId;
		this.updtDt = updtDt;
		this.updtUserId = updtUserId;
	}

	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public String getAdrLine1() {
		return this.adrLine1;
	}

	public void setAdrLine1(String adrLine1) {
		this.adrLine1 = adrLine1;
	}

	public String getAdrLine2() {
		return this.adrLine2;
	}

	public void setAdrLine2(String adrLine2) {
		this.adrLine2 = adrLine2;
	}

	public String getCityNm() {
		return this.cityNm;
	}

	public void setCityNm(String cityNm) {
		this.cityNm = cityNm;
	}

	public String getStateCd() {
		return this.stateCd;
	}

	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}

	public String getZipCd() {
		return this.zipCd;
	}

	public void setZipCd(String zipCd) {
		this.zipCd = zipCd;
	}

	public Date getCrtdDt() {
		return this.crtdDt;
	}

	public void setCrtdDt(Date crtdDt) {
		this.crtdDt = crtdDt;
	}

	public String getCreateUsrId() {
		return this.createUsrId;
	}

	public void setCreateUsrId(String createUsrId) {
		this.createUsrId = createUsrId;
	}

	public Date getUpdtDt() {
		return this.updtDt;
	}

	public void setUpdtDt(Date updtDt) {
		this.updtDt = updtDt;
	}

	public String getUpdtUserId() {
		return this.updtUserId;
	}

	public void setUpdtUserId(String updtUserId) {
		this.updtUserId = updtUserId;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addressId == null) ? 0 : addressId.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Address other = (Address) obj;
		if(this.addressId == null && other.addressId == null){
			return false;//can't compare
		}
		if (addressId == null) {
			if (other.addressId != null)
				return false;
		} else if (!addressId.equals(other.addressId))
			return false;
		return true;
	}
	
	

}
