use cds;

CREATE TABLE `lookup_sex_cd` (
  `SEX_CD` varchar(2) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `SEX_CD_SHORT_TXT` varchar(10) COLLATE utf8_bin NOT NULL,
  `SEX_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`SEX_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `lookup_yn_cd` (
  `YN_CD` varchar(2) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `YN_CD_SHORT_TXT` varchar(10) COLLATE utf8_bin NOT NULL,
  `YN_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`YN_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `lookup_relation_cd` (
  `RELATION_CD` varchar(2) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `RELATION_CD_SHORT_TXT` varchar(20) COLLATE utf8_bin NOT NULL,
  `RELATION_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`RELATION_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `lookup_incometype_cd` (
  `INCOMETYPE_CD` varchar(2) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `INCOMETYPE_CD_SHORT_TXT` varchar(20) COLLATE utf8_bin NOT NULL,
  `INCOMETYPE_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`INCOMETYPE_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `lookup_counties_cd` (
  `COUNTY_CD` varchar(10) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `COUNTY_CD_SHORT_TXT` varchar(20) COLLATE utf8_bin NOT NULL,
  `COUNTY_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`COUNTY_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE `lookup_residenttype_cd` (
  `RESIDENTTYPE_CD` varchar(3) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `RESIDENTTYPE_CD_SHORT_TXT` varchar(400) COLLATE utf8_bin NOT NULL,
  `RESIDENTTYPE_CD_LONG_TXT` varchar(400) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`RESIDENTTYPE_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `lookup_surgery_cd` (
  `SURGERY_CD` varchar(2) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `SURGERY_CD_SHORT_TXT` varchar(20) COLLATE utf8_bin NOT NULL,
  `SURGERY_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`SURGERY_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `lookup_disease_cd` (
  `DISEASE_CD` varchar(3) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `DISEASE_CD_SHORT_TXT` varchar(10) COLLATE utf8_bin NOT NULL,
  `DISEASE_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`DISEASE_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `lookup_severity_cd` (
  `SEVERITY_CD` varchar(2) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `SEVERITY_CD_SHORT_TXT` varchar(10) COLLATE utf8_bin NOT NULL,
  `SEVERITY_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`SEVERITY_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `lookup_plan_details_ym_cd` (
  `PLAN_DETAILS_YM_CD` varchar(3) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `PLAN_DETAILS_YM_CD_SHORT_TXT` varchar(10) COLLATE utf8_bin NOT NULL,
  `PLAN_DETAILS_YM_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`PLAN_DETAILS_YM_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `lookup_incometype_cd` (
  `INCOMETYPE_CD` varchar(2) COLLATE utf8_bin NOT NULL,
  `LANGUAGE_CD` varchar(6) COLLATE utf8_bin NOT NULL,
  `INCOMETYPE_CD_SHORT_TXT` varchar(20) COLLATE utf8_bin NOT NULL,
  `INCOMETYPE_CD_LONG_TXT` varchar(50) COLLATE utf8_bin NOT NULL,
  `SORT_ORDER_NBR` int(11) NOT NULL,
  `ACTIVE_CD` varchar(1) COLLATE utf8_bin NOT NULL DEFAULT 'Y',
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDIT_TS` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`INCOMETYPE_CD`,`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;>>>>>>> .r79
