use cds;


delete from `lookup_sex_cd`;
delete from `lookup_yn_cd`;
delete from `lookup_counties_cd`;
delete from `lookup_relation_cd`;
delete from `lookup_incometype_cd`;
delete from `lookup_residenttype_cd`;
delete from `lookup_lookup_county_details`;
delete from `lookup_surgery_cd`;
delete from `lookup_disease_cd`;
delete from `lookup_severity_cd`;

LOCK TABLES `lookup_county_details` WRITE;
INSERT INTO `lookup_county_details` VALUES ('1', 'Fairfield', '2007', 'Rating Area 1','en_US');
INSERT INTO `lookup_county_details` VALUES ('2', 'HartFord', '2008', 'Rating Area 2','en_US');
INSERT INTO `lookup_county_details` VALUES ('3', 'Litchfield', '2009', 'Rating Area 3','en_US');
INSERT INTO `lookup_county_details` VALUES ('4', 'Middlesex', '2010', 'Rating Area 4','en_US');
INSERT INTO `lookup_county_details` VALUES ('5', 'New Haven', '2011', 'Rating Area 5','en_US');
INSERT INTO `lookup_county_details` VALUES ('6', 'New London', '2012', 'Rating Area 6','en_US');
INSERT INTO `lookup_county_details` VALUES ('7', 'Tolland', '2013', 'Rating Area 7','en_US');
INSERT INTO `lookup_county_details` VALUES ('8', 'Windham', '2014', 'Rating Area 8','en_US');
INSERT INTO `lookup_county_details` VALUES ('9', '001', 'Hawaii', 'Rating Area 1','en_US');
INSERT INTO `lookup_county_details` VALUES ('10', '003', 'Honolulu', 'Rating Area 1','en_US');
INSERT INTO `lookup_county_details` VALUES ('11', '005', 'Honolulu', 'Rating Area 1','en_US');
INSERT INTO `lookup_county_details` VALUES ('12', '007', 'Kaua\'i', 'Rating Area 1','en_US');
INSERT INTO `lookup_county_details` VALUES ('13', '009', 'Maui', 'Rating Area 1','en_US');
UNLOCK TABLES;

>>>>>>> .r79
LOCK TABLES `lookup_sex_cd` WRITE;
/*!40000 ALTER TABLE `lookup_sex_cd` DISABLE KEYS */;
INSERT INTO `lookup_sex_cd` VALUES ('F','en_US','Female','Female',2,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_sex_cd` VALUES ('F','es_US','Mujer','Mujer',2,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_sex_cd` VALUES ('M','en_US','Male','Male',1,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_sex_cd` VALUES ('M','es_US','Hombre','Hombre',1,'Y','2015-05-13 20:50:21',NULL);
/*!40000 ALTER TABLE `lookup_sex_cd` ENABLE KEYS */;
UNLOCK TABLES;


LOCK TABLES `lookup_yn_cd` WRITE;
/*!40000 ALTER TABLE `lookup_yn_cd` DISABLE KEYS */;
INSERT INTO `lookup_yn_cd` VALUES ('N','en_US','No','No',2,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_yn_cd` VALUES ('Y','en_US','Yes','Yes',1,'Y','2015-05-13 20:50:50',NULL);
/*!40000 ALTER TABLE `lookup_yn_cd` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `lookup_counties_cd` WRITE;
/*!40000 ALTER TABLE `lookup_counties_cd` DISABLE KEYS */;
INSERT INTO `lookup_counties_cd`(COUNTY_CD,LANGUAGE_CD,COUNTY_CD_SHORT_TXT,COUNTY_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2007','en_US','Fairfield','Fairfield',1,'Y');
INSERT INTO `lookup_counties_cd`(COUNTY_CD,LANGUAGE_CD,COUNTY_CD_SHORT_TXT,COUNTY_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2008','en_US','HartFord','HartFord',2,'Y');
INSERT INTO `lookup_counties_cd`(COUNTY_CD,LANGUAGE_CD,COUNTY_CD_SHORT_TXT,COUNTY_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2009','en_US','Litchfield','Litchfield',3,'Y');
INSERT INTO `lookup_counties_cd`(COUNTY_CD,LANGUAGE_CD,COUNTY_CD_SHORT_TXT,COUNTY_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2010','en_US','Middlesex','Middlesex',4,'Y');
INSERT INTO `lookup_counties_cd`(COUNTY_CD,LANGUAGE_CD,COUNTY_CD_SHORT_TXT,COUNTY_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2011','en_US','New Haven','New Haven',5,'Y');
INSERT INTO `lookup_counties_cd`(COUNTY_CD,LANGUAGE_CD,COUNTY_CD_SHORT_TXT,COUNTY_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2012','en_US','New London','New London',6,'Y');
INSERT INTO `lookup_counties_cd`(COUNTY_CD,LANGUAGE_CD,COUNTY_CD_SHORT_TXT,COUNTY_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2013','en_US','Tolland','Tolland',7,'Y');
INSERT INTO `lookup_counties_cd`(COUNTY_CD,LANGUAGE_CD,COUNTY_CD_SHORT_TXT,COUNTY_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2014','en_US','Windham','Windham',8,'Y');
/*!40000 ALTER TABLE `lookup_counties_cd` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `lookup_relation_cd` WRITE;
/*!40000 ALTER TABLE `lookup_relation_cd` DISABLE KEYS */;
INSERT INTO `lookup_relation_cd`(RELATION_CD,LANGUAGE_CD,RELATION_CD_SHORT_TXT,RELATION_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('S','en_US','Spouse','Spouse',1,'Y');
INSERT INTO `lookup_relation_cd``(RELATION_CD,LANGUAGE_CD,RELATION_CD_SHORT_TXT,RELATION_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('D','en_US','Dependent','Dependent',2,'Y');
/*!40000 ALTER TABLE `lookup_relation_cd` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `lookup_incometype_cd` WRITE;
/*!40000 ALTER TABLE `lookup_incometype_cd` DISABLE KEYS */;
INSERT INTO `lookup_incometype_cd`(INCOMETYPE_CD,LANGUAGE_CD,INCOMETYPE_CD_SHORT_TXT,INCOMETYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('A','en_US','Annually','Annually',1,'Y');
INSERT INTO `lookup_incometype_cd`(INCOMETYPE_CD,LANGUAGE_CD,INCOMETYPE_CD_SHORT_TXT,INCOMETYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('M','en_US','Monthly','Monthly',2,'Y');
INSERT INTO `lookup_incometype_cd`(INCOMETYPE_CD,LANGUAGE_CD,INCOMETYPE_CD_SHORT_TXT,INCOMETYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('W','en_US','Weekly','Weekly',3,'Y');
/*!40000 ALTER TABLE `lookup_incometype_cd` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `lookup_residenttype_cd` WRITE;
/*!40000 ALTER TABLE `lookup_residenttype_cd` DISABLE KEYS */;
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('1','en_US','Refugee','Refugee',1,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('2','en_US','Asylee','Asylee',2,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('3','en_US','Cuban/Haitian Entrant','Cuban/Haitian Entrant',3,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('4','en_US','Victim of a severe form of trafficking','Victim of a severe form of trafficking',4,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('5','en_US','Alien whose deportation is being withheld','Alien whose deportation is being withheld',5,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('6','en_US','An honorably discharged veteran','An honorably discharged veteran',6,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('7','en_US','On active duty in the U.S. military','On active duty in the U.S. military',7,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('8','en_US','The spouse (including a surviving spouse who has not remarried) or unmarried dependent child of an honorably discharged veteran or individual on active duty in the U.S. military','The spouse (including a surviving spouse who has not remarried) or unmarried dependent child of an honorably discharged veteran or individual on active duty in the U.S. military',8,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('9','en_US','Aliens admitted to the country as an Amerasian immigrant','Aliens admitted to the country as an Amerasian immigrant',9,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('10','en_US','Legal permanent resident who first entered the country under another exempt category (i.e. as a refugee, asylee, Cuban or Haitian entrant, trafficking victim, or alien whose deportation was being withheld) and who later converted to LPR status','Legal permanent resident who first entered the country under another exempt category (i.e. as a refugee, asylee, Cuban or Haitian entrant, trafficking victim, or alien whose deportation was being withheld) and who later converted to LPR status',10,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('11','en_US','Member of a Federally-recognized Indian tribe, as defined in 25 U.S.C. 450b(e)','Member of a Federally-recognized Indian tribe, as defined in 25 U.S.C. 450b(e)',11,'Y');
INSERT INTO `lookup_residenttype_cd`(RESIDENTTYPE_CD,LANGUAGE_CD,RESIDENTTYPE_CD_SHORT_TXT,RESIDENTTYPE_CD_LONG_TXT,SORT_ORDER_NBR,ACTIVE_CD) VALUES ('12','en_US','American Indian born in Canada to whom ?289 of the Immigration and Nationality Act applies','American Indian born in Canada to whom ?289 of the Immigration and Nationality Act applies',12,'Y');
/*!40000 ALTER TABLE `lookup_residenttype_cd` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `lookup_surgery_cd` WRITE;
/*!40000 ALTER TABLE `lookup_surgery_cd` DISABLE KEYS */;
INSERT INTO `lookup_surgery_cd` VALUES ('AG','en_US','Angiogram','Angiogram',1,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('AG','es_US','Angiogram','Angiogram',1,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('AP','en_US','Angioplasty','Angioplasty',2,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('AP','es_US','Angioplasty','Angioplasty',2,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('AD','en_US','Appendectomy','Appendectomy',3,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('AD','es_US','Appendectomy','Appendectomy',3,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('AR','en_US','Arth Knee Surg','Arthroscopic Knee Surgery',4,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('AR','es_US','Arth Knee Surg','Arthroscopic Knee Surgery',4,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('BB','en_US','Breast Biopsy','Breast Biopsy',5,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('BB','es_US','Breast Biopsy','Breast Biopsy',5,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('CS','en_US','Cardiac Stent','Cardiac Stent',6,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('CS','es_US','Cardiac Stent','Cardiac Stent',6,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('CD','en_US','C-Sec Delivery','C-Sec Delivery',7,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('CD','es_US','C-Sec Delivery','C-Sec Delivery',7,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('HS','en_US','Hysterectomy','Hysterectomy',8,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('HS','es_US','Hysterectomy','Hysterectomy',8,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('ID','en_US','Norm Infant Del','Normal Infant Delivery',9,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('ID','es_US','Norm Infant Del','Normal Infant Delivery',9,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('OH','en_US','Open Heart Surg','Open Heart Surgery',10,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('OH','es_US','Open Heart Surg','Open Heart Surgery',10,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('PH','en_US','Partial Hip Rep','Partial Hip Replacement',11,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('PH','es_US','Partial Hip Rep','Partial Hip Replacement',11,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('PK','en_US','Partial Knee Rep','Partial Knee Replacement',12,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('PK','es_US','Partial Knee Rep','Partial Knee Replacement',12,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('TH','en_US','Total Hip Rep','Total Hip Replacement',13,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('TH','es_US','Total Hip Rep','Total Hip Replacement',13,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('TK','en_US','Total Knee Rep','Total Knee Replacement',14,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('TK','es_US','Total Knee Rep','Total Knee Replacement',14,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('TC','en_US','Tracheotomy','Tracheotomy',15,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('TC','es_US','Tracheotomy','Tracheotomy',15,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('NO','en_US','None','None',16,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_surgery_cd` VALUES ('NO','es_US','None','None',16,'Y','2015-05-13 20:50:50',NULL);
/*!40000 ALTER TABLE `lookup_surgery_cd` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `lookup_disease_cd` WRITE;
/*!40000 ALTER TABLE `lookup_disease_cd` DISABLE KEYS */;
INSERT INTO `lookup_disease_cd` VALUES ('ADH','en_US','ADHD','ADHD',1,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('ADH','es_US','ADHD','ADHD',1,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('ART','en_US','Arthritis','Arthritis',2,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('ART','es_US','Arthritis','Arthritis',2,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('AST','en_US','Asthma','Asthma',3,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('AST','es_US','Asthma','Asthma',3,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('ASD','en_US','AsthDia','Asthma, Diabetes',4,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('ASD','es_US','AsthDia','Asthma, Diabetes',4,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CAN','en_US','Cancer','Cancer',5,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CAN','es_US','Cancer','Cancer',5,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CHC','en_US','CarHypCho','Cardiac, Hypertension, Cholesterol',6,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CHC','es_US','CarHypCho','Cardiac, Hypertension, Cholesterol',6,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CHD','en_US','CHD','CHD',7,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CHD','es_US','CHD','CHD',7,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CHF','en_US','CHF','CHF',8,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CHF','es_US','CHF','CHF',8,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CKD','en_US','CKD','CKD',9,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('CKD','es_US','CKD','CKD',9,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('COP','en_US','COPD','COPD',10,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('COP','es_US','COPD','COPD',10,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DEP','en_US','Depress','Depression',11,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DEP','es_US','Depress','Depression',11,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DLR','en_US','DesLesRet','Destruction of Lesion of Retina',12,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DLR','es_US','DesLesRet','Destruction of Lesion of Retina',12,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DIA','en_US','Diabetes','Diabetes',13,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DIA','es_US','Diabetes','Diabetes',13,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DIC','en_US','DiaCar','Diabetes, Cardiac',14,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DIC','es_US','DiaCar','Diabetes, Cardiac',14,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DCC','en_US','DiaCarCho','Diabetes, Cardiac, Cholesterol',15,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DCC','es_US','DiaCarCho','Diabetes, Cardiac, Cholesterol',15,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DCH','en_US','DiaCarHyp','Diabetes, Cardiac, Hypertension',16,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DCH','es_US','DiaCarHyp','Diabetes, Cardiac, Hypertension',16,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DDH','en_US','DiaHyp','Diabetes, Hypertension',17,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('DDH','es_US','DiaHyp','Diabetes, Hypertension',17,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HED','en_US','Heart','Heart Diseases',18,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HED','es_US','Heart','Heart Diseases',18,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HLD','en_US','HypLipDem','Hyperlipidemia',19,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HLD','es_US','HypLipDem','Hyperlipidemia',19,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HPT','en_US','HypTen','Hypertension',20,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HPT','es_US','HypTen','Hypertension',20,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HPC','en_US','HypCar','Hypertension, Cardiac',21,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HPC','es_US','HypCar','Hypertension, Cardiac',21,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HCO','en_US','HypCho','Hypertension, Cholesterol',22,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('HCO','es_US','HypCho','Hypertension, Cholesterol',22,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('OSP','en_US','Osteo','Osteoporosis',23,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('OSP','es_US','Osteo','Osteoporosis',23,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('RAR','en_US','RheuArth','Rheumatoid Arthritis',24,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('RAR','es_US','RheuArth','Rheumatoid Arthritis',24,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('STR','en_US','Stroke','Stroke',25,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('STR','es_US','Stroke','Stroke',25,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('NON','en_US','None','None',26,'Y','2015-05-13 20:50:50',NULL);
INSERT INTO `lookup_disease_cd` VALUES ('NON','es_US','None','None',26,'Y','2015-05-13 20:50:50',NULL);
/*!40000 ALTER TABLE `lookup_disease_cd` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `lookup_severity_cd` WRITE;
/*!40000 ALTER TABLE `lookup_severity_cd` DISABLE KEYS */;
INSERT INTO `lookup_severity_cd` VALUES ('N','en_US','N/A','N/A',1,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_severity_cd` VALUES ('N','es_US','N/A','N/A',1,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_severity_cd` VALUES ('W','en_US','Managed','Managed Well',2,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_severity_cd` VALUES ('W','es_US','Managed','Managed Well',2,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_severity_cd` VALUES ('M','en_US','Moderate','Moderate Status',3,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_severity_cd` VALUES ('M','es_US','Moderate','Moderate Status',3,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_severity_cd` VALUES ('S','en_US','Severe','Severe Status',4,'Y','2015-05-13 20:50:21',NULL);
INSERT INTO `lookup_severity_cd` VALUES ('S','es_US','Severe','Severe Status',4,'Y','2015-05-13 20:50:21',NULL);
/*!40000 ALTER TABLE `lookup_severity_cd` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `lookup_plan_details_ym_cd` WRITE;
/*!40000 ALTER TABLE `lookup_yn_cd` DISABLE KEYS */;
INSERT INTO `lookup_plan_details_ym_cd` VALUES ('Y','en_US','Yearly','Yearly',1,'Y',NULL,NULL);
INSERT INTO `lookup_plan_details_ym_cd` VALUES ('M','en_US','Monthly','Monthly',2,'Y',NULL,NULL);
/*!40000 ALTER TABLE `lookup_yn_cd` ENABLE KEYS */;
UNLOCK TABLES;

INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg1','en_US','GLOBAL','Please select pregnancy status for {0}');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg2','en_US','GLOBAL','Please select relation');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg3','en_US','GLOBAL','Please enter household income');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg4','en_US','GLOBAL','Please select household income type');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg5','en_US','GLOBAL','Please set American Indian or Alaskan native tribe Status');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg6','en_US','GLOBAL','Please select lawful resident');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg7','en_US','GLOBAL','Please select county');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg8','en_US','GLOBAL','Please enter age for {0}');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg9','en_US','GLOBAL','Please select legal status type for {0}');
INSERT INTO `display_text`(text_key,text_lang_cd,service_provider_id,text_val) VALUES ('msg.household.msg10','en_US','GLOBAL','Please select at least one member who has not been lawful resident for at least five');

